//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassensystemPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abrechnungen
    {
        public int AbrechnungsID { get; set; }
        public Nullable<decimal> SollBestand { get; set; }
        public Nullable<System.DateTime> AbrechnungsDatum { get; set; }
    }
}
