//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassensystemPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public int Artikelnr { get; set; }
        public string Artikelbez { get; set; }
        public Nullable<decimal> Nettopreis { get; set; }
        public Nullable<int> Kategorie { get; set; }
        public Nullable<int> Steuersatz { get; set; }
    
        public virtual Kategorieliste Kategorieliste { get; set; }
    }
}
