//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassensystemPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaktionen
    {
        public int RechnungsID { get; set; }
        public Nullable<decimal> NettoGesamtBetrag { get; set; }
        public Nullable<decimal> Steuer { get; set; }
        public Nullable<decimal> BruttoBetrag { get; set; }
        public Nullable<System.DateTime> RechnungsDatum { get; set; }
        public Nullable<int> AbrechnungsID { get; set; }
        public Nullable<int> StornoVon { get; set; }   // RechnungsID der stornierten Originalbuchung
        public string Zahlart { get; set; }            // "Bar" / "Karte"
    }
}
