//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KassensystemPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnternnehmensDaten
    {
        public int UnternehmensID { get; set; }
        public string Name { get; set; }
        public string Strasse { get; set; }
        public Nullable<int> Hausnummer { get; set; }
        public Nullable<int> PLZ { get; set; }
        public string Ort { get; set; }
        public Nullable<long> Tel { get; set; }
        public Nullable<long> Steuernummer { get; set; }
    }
}
